version: '3.8'

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb1
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql


  web:
    build: .
    command: gunicorn book_catalog.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: book_catalog.settings
      MYSQL_DATABASE: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: mariadb1
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_HOST: db
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mariadb_data: